# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# and
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: python
python:
  - 2.7
# Need to set this so that packages installed with apt-get are available
virtualenv:
  system_site_packages: true
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION sphinx
  - pip install -q --use-mirrors sphinx_bootstrap_theme==0.4.5
install:
script:
  - make linkcheck
  - make html
after_success:
  - bash .push-site.sh
