name: geofisica2
dependencies:
    - python=2.7
    - pip
    - numpy
    - scipy
    - matplotlib=1.5
    - numba
    - future
    - pillow
    - jupyter
    - ipython
    - ipywidgets
    - h5py
    - pip:
        - https://github.com/fatiando/fatiando/archive/wavefd.zip
