name: geofisica2
channels:
    - conda-forge
dependencies:
    - python=2.7
    - pip
    - numpy=1.14.2
    - scipy=1.0.0
    - matplotlib=2.2.2
    - numba=0.37
    - future=0.16.0
    - pillow=5.0.0
    - jupyter=1.0.0
    - ipython=5.5.0
    - ipywidgets=7.1.2
    - notebook=5.4.1
    - h5py=2.7.1
    - hdf5=1.10.1
    - ffmpeg=3.4.2
    - pip:
        - https://github.com/fatiando/fatiando/archive/wavefd.zip
